### PR TITLE
Update generated code for Linguist 7.14.0

### PR DESCRIPTION
**Pull request by look**
This time, this is actually the latest version of Linguist. I was hoping to get this into the [2.7.0 release](https://github.com/go-enry/go-enry/releases/tag/v2.7.0) but didn't get it done in time.

### CODE REVIEW

**Comment by lafriks** [comment]
Please update also Linguist version number in README.md

**Review by lafriks — APPROVED** [review]

**Review by elireisman — APPROVED** [review]
Nice, this looks great. Brings in a lot of useful updates 👍

**Comment by mcuadros** [comment]
@lafriks @bzz we should merge this right?

**Comment by lafriks** [comment]
yes, looks good to me

**Comment by look** [comment]
Gentle bump. Can we get this merged? I'd like to deploy it to improve language detection. 🙇

**Comment by imagejan** [comment]
Note that `linguist` is now at [`v7.15.0`](https://github.com/github/linguist/releases/tag/v7.15.0).

**Comment by lafriks** [comment]
@look can you please update to latest version?

**Comment by lafriks** [comment]
@bzz can you please give me PR merge and tagging rights?

**Review by bzz — APPROVED** [review]
Sorry for delay, can merge now or wait in case @look wants to update it.

**Comment by look** [comment]
Please go ahead and merge this PR (I’m afk for a few days). I will prepare
another one for the new release of Linguist.

**Pull request merged**
