### PR TITLE
ci: bump Go versions to two latest ones

### PR DESCRIPTION
**Pull request by bzz**
test plan: CI is 🟢

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Looks like files need to be reformatted as go 1.19 did change some things in formatting go 1.19 formatted files will be ok also for previous versions but not other way around

**Comment by bzz** [comment]
Indeed, [it seems that](https://tip.golang.org/doc/go1.19#go-doc) introduction of https://tip.golang.org/doc/comment has broken the code generator tests.

I also have missed changing version for [oniguruma profiles](https://github.com/go-enry/go-enry/pull/148/files#diff-8622874b888026e1d7c363bf355ce2c7fb38b4bda4109b063b9bb0ac8f50c8cbR29) 🤦

**Comment by bzz** [comment]
> go 1.19 formatted files will be ok also for previous versions but not other way around

No luck! Now profiles <1.19 fail...

**Comment by bzz** [comment]
That is rather annoying as actual change c696f91 is minuscule. Seems to have something to do with https://tip.golang.org/doc/comment#lists 🤔

**Comment by lafriks** [comment]
try [gofumpt](https://github.com/mvdan/gofumpt)

**Comment by bzz** [comment]
I remember fixing this once, when moving from 1.10 to 1.11 🙄 baefa18475971968998071fb6f92c4b1c48e2aa1
Never before, and yet again..

**Comment by bzz** [comment]
There was no need to change the tests, as, indeed, they are formatting proof-ed. The error reporting though is unhelpful as ATM there is no way to print a nice diff of two very long strings.

The reason was in the very last sentence of https://tip.golang.org/doc/comment#lists
> It inserts a blank line between a list and the following paragraph or heading.

and in the initial `.tmpl` update 314a889316fd9c5edb9c27abf8a18a49b653b389 I have missed this 🤦. 

Now history was-rewritten, a newline added and everything works.

It would have been discovered much faster if [generator tests](https://github.com/go-enry/go-enry/blob/fcb9ea7e4589ccfaebc0263c2dc2dc5533801a0b/internal/code-generator/generator/generator_test.go#L324) would produce a helpful diff between the .gold and generated code!

Go 1.19, specifically for the formatter tests, has landed a nice string diff library https://go-review.googlesource.com/c/go/+/384255 but it is internal and I did not try it for the case of 2 long (normalized, i.e. \wo newlines) strings. At least with the standard `diff` it's not that helpful after the normalisation.

**Comment by lafriks** [comment]
Nice, hopefully go won't break such things so much in the future :)

**Pull request merged**
