### PR TITLE
Sync with github/linguist version v7.12.2

### PR DESCRIPTION
**Pull request by lafriks**
Update to latest version https://github.com/github/linguist/releases/tag/v7.12.2

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me, thanks! Shall we release a new version as well?

**Review by bzz — APPROVED** [review]

**Comment by lafriks** [comment]
Yes, new version would be nice

**Comment by lildude** [comment]
👋 from Linguist. You might want to bump to 7.13.0 before you make a new release as I released v7.13.0 yesterday.

**Comment by lafriks** [comment]
@lildude 👋 thanks for notice, I will check that out 😉

**Comment by bzz** [comment]
Thanks, and sorry for delay. Going to merge this and wait for v7.13.0 sync before 🔪  a release then.

**Pull request merged**
