### PR TITLE
Update Linguist to v7.23.0 with build-time checks

### PR DESCRIPTION
**Pull request by bzz**
This is the #137 with the #151. 

It is a better alternative to #139.

### CODE REVIEW

**Comment by bzz** [comment]
The test failures now are miss-classifications due to RE2-incompatible syntax for new content heuristics

```
     linguist_corpus_test.go:35
            	Error:      	Not equal: 
            	            	expected: "Adblock Filter List"
            	            	actual  : "Text"
```

and from `make code-generate` logs we have

```
2023/01/19 19:57:45 RE2 incompatible syntax for heuristic language:'[Adblock Filter List]', rule:'(?x)\A
\[
(?<version>
  (?:
    [Aa]d[Bb]lock
    (?:[ \t][Pp]lus)?
    |
    u[Bb]lock
    (?:[ \t][Oo]rigin)?
    |
    [Aa]d[Gg]uard
  )
  (?:[ \t] \d+(?:\.\d+)*+)?
)
(?:
  [ \t]?;[ \t]?
  \g<version>
)*+
\]'
```

These should be addressed in this PR, adding them to https://github.com/go-enry/go-enry#divergences-from-linguist after #151  is merged.

**Comment by bzz** [comment]
Oh, no - something seems to be missing as oniguruma profile fails. Going to fix that in #151 first

**Comment by bzz** [comment]
Default CI profile (using RE2) failures represent divergence between linguist regex syntax (ruby) and RE2 (go).
We are only aiming to get Oniguruma ones 🟢  here. The rest should be addressed in #137, as usual.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
If I understand correctly that failing tests will be addressed in #137?

**Comment by bzz** [comment]
> If I understand correctly that failing tests will be addressed in https://github.com/go-enry/go-enry/pull/137?

that is correct, there (or in a new PR) - this was just an integration branch to test the #151.

**Pull request closed without merging**
