### PR TITLE
data: replace substring package with regex package

### PR DESCRIPTION
**Pull request by mcuadros**
This PR remote the old `substring` package from @toqueteos (sorry dude) and use the internal `regex` package to use oniguruma regexp with all the regular expressions.

### CODE REVIEW

**Comment by lafriks** [comment]
But it will be performance degradation in case where onigurama is not used. At least in Gitea we have no such option. I had impression that substring package has about the same performance as onigurama

**Comment by mcuadros** [comment]
Substring was designed to avoid the usage of regexp, original we were using other methods from the library, but today we were only using `regexp` with is exactly the same as using directly `EnryRegexp`. 

https://github.com/toqueteos/substring/blob/v2/string.go#L16

**Comment by lafriks** [comment]
I thought it was analyzing regexp and improves speed for simple ones

**Comment by toqueteos** [comment]
No need to be sorry, it solved a problem you seem to not have anymore!

**Pull request merged**
