### PR TITLE
Update to Linguist v7.16.1

### PR DESCRIPTION
**Pull request by lafriks**
Depends on #58

### CODE REVIEW

**Comment by bzz** [comment]
Thank you for keeping it up-to-date 🚀 
#58 is merged, so a rebase is in order

**Comment by lafriks** [comment]
@bzz rebased

**Comment by lafriks** [comment]
would be nice to tag new version once this is merged

**Review by bzz — APPROVED** [review]

**Comment by bzz** [comment]
> would be nice to tag new version once this is merged

https://github.com/go-enry/go-enry/releases/tag/v2.7.2

**Comment by lafriks** [comment]
Not that I would mind much but there is wrong additional reference to PR for shebang and contributors section seems also not correct :)

**Comment by bzz** [comment]
> @bzz Not that I would mind much but there is wrong additional reference to PR for shebang and contributors section seems also not correct :)

Thank you very much for catching that!

**Pull request merged**
