### PR TITLE
Refactoring tests

### PR DESCRIPTION
**Pull request by bzz**
Several cosmetic changes
 * API function declarations order follows tests order
 * Linguist lazy loading logic unified & re-used, as much as possible between tests&benchmark
 * Separate test suite extracted for running over Linguist samples/fixtures

### CODE REVIEW

**Comment by bzz** [comment]
Pyhton test cases are failing on Python 3.6 install and are not relevant.

**Comment by lafriks** [comment]
looks like python 3.6 has been dropped, we should probably update to use python 3.8, 3.9 and 3.10

**Comment by bzz** [comment]
> looks like python 3.6 has been dropped, we should probably update to use python 3.8, 3.9 and 3.10

Addressed in #147 as, as noted, it is not related to the change at hand. 

Planning to merge, if there is no further discussion.

**Review by lafriks — APPROVED** [review]

**Comment by bzz** [comment]
Thank you for the review! Rebased on latest master, all CI is green.

**Pull request merged**
