### PR TITLE
Add support for Roff man pages filenames

### PR DESCRIPTION
**Pull request by lafriks**
Ref: https://github.com/github/linguist/commit/29912736c6e9d52545687d20b97bac83c8298cce

### CODE REVIEW

**Comment by bzz** [comment]
For the purpose of simplifying future maintenance, it will be a good idea to follow the linguist convention and same as with all other strategies - just define a new `Strategy` and add it to the right place in the `DefaultStrategies` ?

**Comment by lafriks** [comment]
At first I started doing so but that would mean refactoring also other code and would mean that function to detect by extension would not detect roff man pages while they are purely detection by extension/filename

**Comment by bzz** [comment]
Hm, but from what I can see in https://github.com/github/linguist/pull/4393/files - it does not seem to be possible to tell some cases of Roff manpages only from the filename already 🤔 

But I see you point.

To mitigate my concern about the maintenance, the simplest way I can see is: 
 - localise the impact by grouping all the code together (move var declaration inside the function, before its usage) and 
 - document it, by writing a comment, explaining that although https://github.com/github/linguist/commit/29912736c6e9d52545687d20b97bac83c8298cce has is as a separate strategy - it is only extension-based and so we put it inside Extension one (or words to that effect)
 - update https://github.com/go-enry/go-enry#divergences-from-linguist adding another point, mentioning that the Manpage strategy got folded into the Extension one

Let me know what you think!

**Comment by lafriks** [comment]
> Hm, but from what I can see in https://github.com/github/linguist/pull/4393/files - it does not seem to be possible to tell some cases of Roff manpages only from the filename already, no? thinking

Linguist Manpage strategy (from code point of view) does check only filename to match regexp so file content does not play any role (except for possibly training classifier).

Anyway to be more in par with Linguist I have split it out to other strategy function.

As for defined variable imho it should be defined outside function to not have to parse regexp on every function call

**Review by bzz — APPROVED** [review]
Thanks, that makes perfect sense and looks great to me!

**Pull request merged**
